### ISSUE TITLE
[BUG] goshs 0.1.6 can be crashed using the clipboard

### ISSUE THREAD

**Issue by IIpho3nix** [patrickhener/goshs#21]
### how to replicate
1. open goshs at any directory
2. add 3 notes
3. starting removing notes starting from the first one
4. goshs will crash
 ### stacktrace
```
panic: runtime error: slice bounds out of range [2:1]

goroutine 107 [running]:
github.com/patrickhener/goshs/internal/myclipboard.(*Clipboard).DeleteEntry(...)
        /home/runner/work/goshs/goshs/internal/myclipboard/clipboard.go:51
github.com/patrickhener/goshs/internal/mysock.(*Client).readPump(0xc0000d0048)
        /home/runner/work/goshs/goshs/internal/mysock/client.go:113 +0x73f
created by github.com/patrickhener/goshs/internal/mysock.ServeWS
        /home/runner/work/goshs/goshs/internal/mysock/client.go:202 +0x19f

```

### possible cause
goshs seems to think arrays start at 1 when the notes are removed
![image](https://user-images.githubusercontent.com/79083095/150630322-772767e4-096c-4f96-8efc-9948ed41414f.png)

**Comment by patrickhener** [comment]
Thanks for reporting. I will look into it as soon as I have some spare time.

**Comment by patrickhener** [comment]
replicate by creating 3 clipboard entries. Then delete first one (index 0) then last one.

**Comment by patrickhener** [comment]
> goshs seems to think arrays start at 1 when the notes are removed image
It is more a problem of, when index 0 is deleted the indexes are not rearranged, like it happens if for example index 1 is removed.

**Comment by patrickhener** [comment]
Commit b45ddef should fix this issue by reindexing the entries when one gets deleted
