### ISSUE TITLE
Sort by date

### ISSUE THREAD

**Issue by Barmem** [patrickhener/goshs#26]
Sort by date seems to be acting weird, is it sorting by alphabetical order?![IMG_20220411_211108.jpg](https://user-images.githubusercontent.com/70278808/162771507-08aaf24e-e10d-4a20-83f1-3035ab2a9dd5.jpg)

**Comment by patrickhener** [comment]
Oh that is odd. I will have to investigate myself. Will give it a try tomorrow (German time)

**Comment by patrickhener** [comment]
This is odd. For me it sorts totally perfect. So I need further information to maybe reproduce.
On what os is it running?
This is the current version?
Which browser do you use?

**Comment by Barmem** [comment]
hosting on windows, opening in android chrome

**Comment by patrickhener** [comment]
I am more than sorry but in my case in this environment the sorting works fine. My environment is all en-US. Does yours differ?

**Comment by Barmem** [comment]
ru-RU i would guess

**Comment by patrickhener** [comment]
Solved with commit 4732ae3 and version v0.3.3. Please do `go install github.com/patrickhener/goshs@latest`

**Comment by Barmem** [comment]
looks like its fixed, thanks
