### ISSUE TITLE
web ui not responsive and file upload missing

### ISSUE THREAD

**Issue by 0xhunster** [patrickhener/goshs#28]
before
![image](https://user-images.githubusercontent.com/46501627/167119884-6992cc1d-316f-4a9c-becc-5e38b4c0d19d.png)

when I drag and drop my folder web UI looks like
![image](https://user-images.githubusercontent.com/46501627/167120164-732ad967-0ec6-46c6-899c-cca9b6c4baf7.png)
![image](https://user-images.githubusercontent.com/46501627/167120270-75de4f41-220c-4694-94b0-ab77fd03285e.png)

after
![image](https://user-images.githubusercontent.com/46501627/167120424-09851ef6-1b41-4ff1-a2a6-fa7aeec6f851.png)

**Comment by patrickhener** [comment]
Yeah. Those are too much files I suppose. So either zip them beforehand and transfer in one file or go in batches.
