### ISSUE TITLE
BUG: Firefox is complaining about MIME types

### ISSUE THREAD

**Issue by MrFaul** [patrickhener/goshs#34]
### MIME types...
Somehow goshs confuses MIME types and sends all files as "text/plain"
Now Chromium based browsers doesn't seem to be bothered at all, but Firefox is nagging about JS and even refuses CSS files outright.
The OS (in this case Linux) recognizes the MIME type correctly so that's not an issue. (Its a simple file ending after all)
Frankly I'm at a loss here.

Maybe I'm just dumb 🤷
I use goshs for a dirty little HTML dev tool for prototyping,
so I'm just dumping everything in a folder and serve that.
Or is there any configuration needed for the correct classification of MIME types?

**Comment by patrickhener** [comment]
Hi Tim and thanks for sending the Bug. I will look into it and return to you once I have a general idea what is going on.

**Comment by patrickhener** [comment]
So this is my test setup
[files.zip](https://github.com/patrickhener/goshs/files/10838678/files.zip)
I am serving this 3 files from a directory and then use goshs to serve them. Then I browse to index.html

**Comment by patrickhener** [comment]
![Using Firefox 110.0 on Linux](https://user-images.githubusercontent.com/7579055/221541157-fe4708ba-e6ad-41be-bf7e-424678147d6c.png)
![Using Chromium 110.0.5481.100 on Linux](https://user-images.githubusercontent.com/7579055/221541459-19679849-d679-4bfe-b5ef-98e66abfa1a8.png)

In both cases my browser do interpret the files although delivered as text/plain, as you can see from the screenshots. Let me check if I can make goshs deliver them correctly.

**Comment by patrickhener** [comment]
![Correct Mime Type](https://user-images.githubusercontent.com/7579055/221545333-7223b672-b859-49f8-9488-d0ae0a7745e7.png)
So minor changes to the code will now deliver the files with a correct mime type.
Commit d280f4fa92984bfafca87212cba1c785ac92632a will now include the changes. See and try out if this fixes your issues.

**Comment by patrickhener** [comment]
Is solved with pull request #36  .

**Comment by MrFaul** [comment]
Ah sry was pre occupied with other stuff.
Completely forgot to give feed back.
Thx works as advertised 👍

Patrick Hener ***@***.***> schrieb am Di., 28. Feb. 2023,
15:57:
