### ISSUE TITLE
doc issue - build fails on missing uglifyjs and mt

### ISSUE THREAD

**Issue by clach04** [patrickhener/goshs#37]
Follow instructions in readme for build https://github.com/patrickhener/goshs/blob/83bb70eff75195dc5fae75f8dbfb8dc8af9e8523/README.md?plain=1#L46

will get failure due to undocumented base requirements.

https://github.com/patrickhener/goshs/blob/83bb70eff75195dc5fae75f8dbfb8dc8af9e8523/Makefile#L6

**Comment by patrickhener** [comment]
Thanks for bringing this to my attention. You are totally correct. I am missing crucial details in the README.md to point out what are the requirements for manual building. Let me fix that real quick.

**Comment by patrickhener** [comment]
Documentation was fixed to account for the requirements when building manually.
