### ISSUE TITLE
[Feature] Only use stdlib again (Req: Go 1.16)

### ISSUE THREAD

**Issue by patrickhener** [patrickhener/goshs#4]
As Go 1.16 might have the function to embed static files within the binary with a stdlib (proposal is already accepted) I need to ditch parcello in favor of it. I will handle this issue after Go 1.16 is here (Febuary - ish 2021?)

**Comment by Yanwenjiepy** [comment]
yes, I am looking forward

**Comment by patrickhener** [comment]
Well right now I am also using gorilla/mux and am planning on using tcell for a tui I am planning on. So I cannot promise that there will be a time I am using stlib only again.

**Comment by patrickhener** [comment]
Solved with 5cad36366d3f7092c74513c2626c2f01a16afdf7
