### ISSUE TITLE
Feature Request: Option to change to unprivileged UID/GID after TLS certs read

### ISSUE THREAD

**Issue by aWZHY0yQH81uOYvH** [patrickhener/goshs#40]
It would be nice to have the option to drop privileges after starting up (like Apache switching to the `www-data` user) to mitigate file inclusion vulnerabilities and further protect manually-supplied TLS certs that may be root-owned (and have 600 permissions).

I see this would require a bit more than just a call to `setuid` since the server is handled by an external Go module, so perhaps this would be more effort than it's worth in a testing/non-permanent application like this.

**Comment by patrickhener** [comment]
Well if you run `goshs` as a user then only files can be read the user can read, right? So imagine running it as user `patrick` in the root (`/`) I would not be able to read `/etc/shadow`. 

![Error message in UI](https://user-images.githubusercontent.com/7579055/236764378-6da705aa-6cdd-4c3a-b9fa-561effc583e7.png)
![Error on console](https://user-images.githubusercontent.com/7579055/236764484-007cb956-d058-480e-9136-efb6bc341ee6.png)

So either I am misunderstanding your suggestion or `goshs` is already able to do, what you suspect. The only additional thing which comes to my mind is that we could introduce a `--user` flag where you can provide goshs with a username. And then after starting goshs will drop to that privilege. But then again you could just run goshs as this specific user.

**Comment by aWZHY0yQH81uOYvH** [comment]
Yes, it's only really applicable when using the `-sk` and `-sc` options, where those files might be owned and only readable as root. You can make them readable by the less-privileged user and run using `su nobody -c "goshs -sk key.pem -sc cert.pem"`, but then they remain readable by the process as the server runs, which is unnecessary.

**Comment by patrickhener** [comment]
Hi and thanks for clarifying. Now I got your idea. I will need to read into the topic and see if I can make this happen. But as you already said this app is meant to be a quick drop-in replacement for python simple HTTP server or any similar one line web server. So the effort might not be worth the benefit.

**Comment by aWZHY0yQH81uOYvH** [comment]
Thanks! I've been using this project quite a bit the last few weeks and it's been super useful.

A couple things with v0.3.2 however:

I usually run this on FreeBSD which isn't detected [here](https://github.com/patrickhener/goshs/blob/e68e0f0c3a896b8f0f750293336a40c1061eb01c/httpserver/drop_unix.go#LL1C1-L1C1), meaning it won't install. The `GOOS` environment variable is set to `freebsd` which doesn't match `linux` or `darwin`. I think there's a special `unix` specifier that should take care of all the Unix variants.

File-provided certificates seem to be broken. Using the same certs that worked in v0.3.1, v0.3.2 fails with the following error.
```
INFO   [2023-05-26 07:58:44] Serving on interface lo0 bound to 127.0.0.1:8000 
INFO   [2023-05-26 07:58:44] Serving HTTPS from /tmp/serve with ssl enabled server key: test.key, server cert: test.crt 
INFO   [2023-05-26 07:58:44] You provided a certificate and might want to check the fingerprint nonetheless 
INFO   [2023-05-26 07:58:44] SHA-256 Fingerprint: B0 92 7E A4 B2 8C FF AE E3 D8 C4 4F 34 B2 62 35 69 E5 24 5D 8F 56 98 5A 88 B9 E0 1A 44 EA 8F 18  
INFO   [2023-05-26 07:58:44] SHA-1   Fingerprint: B6 E6 67 E1 11 93 1D D7 D3 97 7B D7 C3 CE 18 A4 65 F1 8A 11  
PANIC  [2023-05-26 07:58:44] open : no such file or directory             
panic: (*logrus.Entry) 0xc0001d59d0

goroutine 33 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0001d55e0, 0x0, {0xc00015c140, 0x20})
	/Users/x/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:259 +0x487
github.com/sirupsen/logrus.(*Entry).Log(0xc0001d55e0, 0x0, {0xc0001edd18?, 0x12eba8b?, 0xc0000ea120?})
	/Users/x/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:293 +0x4f
github.com/sirupsen/logrus.(*Entry).Logln(0xc0001d55e0, 0x0, {0xc0001edec8?, 0x0?, 0x0?})
	/Users/x/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/entry.go:383 +0x85
github.com/sirupsen/logrus.(*Logger).Logln(0xc0000ea0e0, 0x0, {0xc0001edec8, 0x1, 0x1})
	/Users/x/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:292 +0x65
github.com/sirupsen/logrus.(*Logger).Panicln(...)
	/Users/x/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/logger.go:333
github.com/patrickhener/goshs/logger.Panic(...)
	/Users/x/go/pkg/mod/github.com/patrickhener/goshs@v0.3.2/logger/logger.go:153
github.com/patrickhener/goshs/httpserver.(*FileServer).Start(0xc000126000, {0x144fd92, 0x3})
	/Users/x/go/pkg/mod/github.com/patrickhener/goshs@v0.3.2/httpserver/server.go:118 +0xc34
created by main.main
	/Users/x/go/pkg/mod/github.com/patrickhener/goshs@v0.3.2/main.go:216 +0x345
```

Is there a missing `server.TLSConfig` assignment after [this](https://github.com/patrickhener/goshs/blob/e68e0f0c3a896b8f0f750293336a40c1061eb01c/httpserver/server.go#L110) line?

**Comment by patrickhener** [comment]
Oh boy. Okay. So I need to Look into that later. Sorry for the issues

**Comment by patrickhener** [comment]
I re-pushed the tag so a new release would be created by the actions. So the go install @latest tag should now have the fixes applied.
