### ISSUE TITLE
How to define the default home page?

### ISSUE THREAD

**Issue by hhackbarth** [patrickhener/goshs#49]
When using goshs as http(s) server, I would like to define, which file from the base directory should be served as home page (e.g. index html).
I found now option or config file for this purpose. Did I oversee something?

**Comment by patrickhener** [comment]
This is not the purpose of the tool. This tool serves as a drop in replacement for `updog` or pythons `simpleHTTPServer/http.server`. So the index page is not changeable. If you want an easy to setup webserver though you could look into caddy2.
