### ISSUE TITLE
[BUG] Files remain occupied after uploading

### ISSUE THREAD

**Issue by closehandle** [patrickhener/goshs#77]
**Describe the bug**
Files remain occupied after upload

**To Reproduce**
1. Start goshs with command `goshs ...`
2. Browse to `http://localhost:8000/...`
3. Upload an file
4. Try to move the uploaded file with Windows Explorer
5. See error

**Expected behavior**
Normally after the upload the file's handle should be closed and the file is no longer occupied

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 19045.4412
 - goshs version: v0.4.1 (Previous versions also had this problem)
 - Browser: edge and firefox
 - Browser version: latest

**Comment by patrickhener** [comment]
So this seems to be a Windows only problem. In linux and macos the file can be moved right after upload.

**Comment by patrickhener** [comment]
I reproduced it on Windows 11 using goshs v0.4.1. What I did is to start goshs, then open a browser (same machine) and upload a file. Then I went to the upload directory, marked the file and cut it (CTRL+X) and pasted it elsewhere, which it did.

Can you clarify if the reproduction steps were correct @closehandle? If so I cannot reproduce it seems.

**Comment by patrickhener** [comment]
Also Line 75-83 in file httpserver/updown.go should take care of closing the file handle:

https://github.com/patrickhener/goshs/blob/6f4834dc85f439126d4a9dd7e53d6e2611f01ccb/httpserver/updown.go#L75-L83

**Comment by closehandle** [comment]
https://github.com/user-attachments/assets/2b23ffae-4af1-40f1-aaed-c45f4057d096

**Comment by patrickhener** [comment]
I don't get the submenu part where you right clicking the file. What does it say?

**Comment by closehandle** [comment]
> I don't get the submenu part where you right clicking the file at seconds 19 and 20. What does it say? And afterwards you double-click the file?

refresh

**Comment by patrickhener** [comment]
Ah I see. You try to delete it, whereas I tried to move it. And what about after exiting `goshs`? The file can be deleted, right?

**Comment by patrickhener** [comment]
Let me try and see what happens if I upload -> right click refresh -> then alt+d aka remove the file.

**Comment by patrickhener** [comment]
Could you please check once again that you have the correct version. When running from powershell it started v0.4.1 for me. In cmd.exe it started v0.3.3 for whatever reason. This version indeed does block the file. After starting the correct version it did work. see and check `goshs -v` or at the bottom of the UI. You could also try and download the release version .exe and start it like `C:\tmp> .\goshs.exe`

**Comment by closehandle** [comment]
```
PS> goshs -v
goshs version is: v0.4.1
```

**Comment by closehandle** [comment]
I put `goshs.exe` in `C:\Windows` so I can use it anywhere without having to add environment variable

**Comment by patrickhener** [comment]
Well that is more than odd. If you upload a small text file. Lets say you have a 1kb file and upload it, then it can be removed. I retested with a bigger msi file (go installation msi) and then I can reproduce the error.

**Comment by patrickhener** [comment]
This only still applies to windows

**Comment by closehandle** [comment]
I noticed that your code doesn't flush the buffer before closing the file handle, in Go it would be `Sync`

**Comment by closehandle** [comment]
> This only still applies to windows

Only Windows has file occupancy, in Linux it is even possible to delete running programs

**Comment by patrickhener** [comment]
So I tried adding the sync and close for the file handle in either 

https://github.com/patrickhener/goshs/blob/6f4834dc85f439126d4a9dd7e53d6e2611f01ccb/httpserver/updown.go#L99-L101

or after the for loop. All I got was:

```
ERROR  [2024-07-25 12:41:24] error closing file: close C:\tmp/go1.22.5.windows-amd64.msi: file already closed
```

Apparently it is already closed but not really for whatever reason. I am not sure how to resolve the issue.

**Comment by closehandle** [comment]
![图片](https://github.com/user-attachments/assets/46f3d736-a30b-4dda-b86f-34f92be7b1ad)
![图片](https://github.com/user-attachments/assets/3ef19953-5378-411c-8ac3-0daaa075b58d)

**Comment by closehandle** [comment]
Okay, so i think i just fixed it, tested multiple times its just works

**Comment by closehandle** [comment]
@patrickhener Can you verify that it works?

**Comment by patrickhener** [comment]
I can indeed confirm that this change will work. I will create a pull request to fix this issue.

**Comment by patrickhener** [comment]
Thanks for contributing and fixing this bug. Very appreciated.

**Comment by closehandle** [comment]
Thanks for your project as well!
